In [ ]:
'''LOGISTIC MAP'''
import numpy as np

# Load input data from a text file
def load_input_data(file_path):
    # Load the data from the text file into a NumPy array
    input_data = np.loadtxt(file_path)  # Load numbers from the file

    # Ensure the input data is reshaped to (1, 131072) if needed
    input_data = input_data.reshape(1, 131072)

    return input_data

# Specify the path to your input text file
input_file_path = r"C:\Users\srisu\Encryption Project\normalized_numbers.txt"  # Update with your actual file path

# Load the input data from the file
X0 = load_input_data(input_file_path)[0]
print("Reshaped Input Data (flattened):", X0)

# Logistic map function for matrix input
def logistic_map_matrix(r, Y):
    return r * Y * (1 - Y)

# Parameters
r = 3.9995467972  # Growth rate
n_generations = 100  # Number of iterations
X = X0[::-1]  # Reverse input data as before
for _ in range(n_generations):
    X = logistic_map_matrix(r, X)

# Save the output to a text file with 131072 values
np.savetxt(
    r"C:\Users\srisu\Encryption Project\logistic_map_output_without_rep.txt",
    X.reshape(131072, 1),  # Reshape output to match the 131072 size
    fmt="%f",
)

print("Logistic Map output generated with 131072 values.")


In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, models, optimizers, callbacks
from tensorflow.keras.losses import MeanSquaredError

# Create the model
def create_model():
    model = models.Sequential([
        layers.InputLayer(input_shape=(65536,)),
        layers.Dense(2048, activation='relu'),
        layers.BatchNormalization(),  # Batch normalization layer
        layers.Dense(1024, activation='relu'),
        layers.BatchNormalization(),
        layers.Dense(65536, activation='sigmoid')
    ])
    return model

# Load input data
def load_input_data(file_path):
    input_data = np.loadtxt(file_path)
    input_data = input_data.reshape(1, 65536)
    return input_data

input_file_path = r"C:\Users\srisu\Encryption Project\logistic_map_output.txt"
input_data = load_input_data(input_file_path)

# Initialize the model
model = create_model()

# Optimizer with gradient clipping
optimizer = optimizers.Adam(learning_rate=0.002, clipnorm=1.3)  # Lower learning rate and clip gradients

# Compile model
model.compile(optimizer=optimizer, loss=MeanSquaredError())

# Early stopping callback
early_stopping = callbacks.EarlyStopping(monitor='loss', patience=15, restore_best_weights=True)

# Train the model
model.fit(input_data, input_data, epochs=200, batch_size=50, callbacks=[early_stopping])

# Predict and save output
output = model.predict(input_data)
np.savetxt(
    r"C:\Users\srisu\Encryption Project\neural_network_output.txt",
    output.reshape(65536, 1),
    fmt='%.20f'
)

print("Training and prediction completed.")

In [5]:
'''CONVERT TO ARRAY'''
import numpy as np

# Load the outputs from the text file and convert them to a NumPy array
def load_outputs_to_array(filename):
    array = np.loadtxt(filename)  # Load the file as a NumPy array
    return array

if __name__ == "__main__":
    output_filename = r"C:\Users\srisu\Encryption Project\normalized_ikeda_map.txt"
    output_array = load_outputs_to_array(output_filename)
    
    # Print the shape and first few elements of the array for verification
    print(f"Array shape: {output_array.shape}")
    print(f"First 5 outputs: {output_array[:5]}")


Array shape: (65536,)
First 5 outputs: [0.59972162 0.58511445 0.43713533 0.69998663 0.59258599]


In [6]:
'''INDEX EXTRACTION (AFTER SORTING)'''
array = output_array
# Get the sorted indices
sorted_indices = np.argsort(array)

# Print the original array and sorted indices
print("Original Array:")
print(array)
print("\nSorted Indices:")
print(sorted_indices)

# Save the sorted indices to a file
np.savetxt(r"C:\Users\srisu\Encryption Project\ikeda_indices.txt", sorted_indices.flatten(), fmt='%d')

# If you want to save the original array for reference, uncomment the line below
# np.savetxt(r'C:\Users\srisu\Encryption Project\original_array.txt', array)

Original Array:
[0.59972162 0.58511445 0.43713533 ... 0.65250302 0.44129706 0.23522537]

Sorted Indices:
[2379 2322 2351 ... 2216 2420 2344]


In [2]:
'''ALTER FINAL INDICES TO MAP VARIABLES'''
import numpy as np

# Load the outputs from the text file and convert them to a NumPy array
def load_outputs_to_array(filename):
    array = np.loadtxt(filename)  # Load the file as a NumPy array
    return array

if __name__ == "__main__":
    output_filename = r"C:\Users\srisu\Encryption Project\final_indices.txt"
    arr = load_outputs_to_array(output_filename)

    # Create lists to hold the segments
    a = arr[0:3276].tolist()
    b = arr[3276:6552].tolist()
    c = arr[6552:9828].tolist()
    d = arr[9828:13104].tolist()
    e = arr[13104:16380].tolist()
    f = arr[16380:19656].tolist()
    g = arr[19656:22932].tolist()
    h = arr[22932:26208].tolist()
    i = arr[26208:29484].tolist()
    j = arr[29484:32760].tolist()
    k = arr[32760:36036].tolist()
    l = arr[36036:39312].tolist()
    m = arr[39312:42588].tolist()
    n = arr[42588:45864].tolist()
    o = arr[45864:49140].tolist()
    p = arr[49140:52416].tolist()
    q = arr[52416:55692].tolist()
    r = arr[55692:58968].tolist()
    s = arr[58968:62244].tolist()
    t = arr[62244:65536].tolist()

    # Combine all lists together
    final = s + n + h + m + j + f + c + t + b + r + g + d + a + l + e + p + i + o + k + q

    # Convert the final list to a numpy array
    final_array = np.array(final)

    # Print the final array
    print(final_array)

[27401.  8157. 49718. ... 26624. 25417.  8637.]


In [4]:
'''FINAL ARRAY EXTRACTION'''
array = final
# Get the sorted indices
sorted_indices = np.argsort(array)

# Save the sorted indices to a file
np.savetxt(r"C:\Users\srisu\Encryption Project\ikeda_and_logistic_indices.txt", sorted_indices.flatten(), fmt='%d')

# If you want to save the original array for reference, uncomment the line below
# np.savetxt(r'C:\Users\srisu\Encryption Project\original_array.txt', array)

In [8]:
'''IKEDA MAP SCRAMBLING'''
'''THIS SEQUENCE OF ADDITION:
  final = s + n + h + m + j + f + c + t + b + r + g + d + a + l + e + p + i + o + k + q
Was calculated using the below code: 
'''
import numpy as np

# Load the outputs from the text file and convert them to a NumPy array
def load_outputs_to_array(filename):
    array = np.loadtxt(filename)  # Load the file as a NumPy array
    return array

if __name__ == "__main__":
    output_filename = r"C:\Users\srisu\Encryption Project\ikeda_map_output.txt"
    arr = load_outputs_to_array(output_filename)
    array = arr
# Get the sorted indices
sorted_indices = np.argsort(array)

# Print the original array and sorted indices
print("Original Array:")
print(array)
print("\nSorted Indices:")
print(sorted_indices)

# Save the sorted indices to a file
np.savetxt(r"C:\Users\srisu\Encryption Project\ikeda_indices.txt", sorted_indices.flatten(), fmt='%d')

# If you want to save the original array for reference, uncomment the line below
# np.savetxt(r'C:\Users\srisu\Encryption Project\original_array.txt', array)

Original Array:
[0.526032 0.488178 0.482768 0.511694 0.531987 0.480702 0.509871 0.447216
 0.550148 0.464216 0.560879 0.531556 0.462722 0.424329 0.556763 0.543312
 0.594508 0.505501 0.406525 0.486049]

Sorted Indices:
[18 13  7 12  9  5  2 19  1 17  6  3  0 11  4 15  8 14 10 16]
